name: Build, test, and publish Docker Images

env:
  OWNER: khiopsml
  IMAGE_NAME: ${{ github.event.repository.name }}

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  schedule:
    # Weekly, at 07:00 on Monday UTC time
    - cron: "0 7 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
      - "Dockerfile"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false
          large-packages: false
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          docker-images: true

      - name: Checkout Repo ‚ö°Ô∏è
        uses: actions/checkout@v4

      - name: Set Up Python üêç
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install Dev Dependencies üì¶
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

      - name: Get commit sha, this will be used as a tag later on üè∑
        shell: bash
        run: |
          sha12=$(echo ${GITHUB_SHA} | cut -c1-12)
          echo "sha12=$sha12" >> "$GITHUB_ENV"
          echo "SHA_TAG=${{ env.OWNER }}/${{ env.IMAGE_NAME }}:$sha12" >> "$GITHUB_ENV"
          echo "LATEST_TAG=${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest" >> "$GITHUB_ENV"
          echo "TEST_TAG=${{ env.OWNER }}/${{ env.IMAGE_NAME }}:test" >> "$GITHUB_ENV"
          echo "V11BETA_TAG=${{ env.OWNER }}/${{ env.IMAGE_NAME }}:11beta" >> "$GITHUB_ENV"
        id: get_sha

      - name: Login to Docker Hub üîê
        uses: docker/login-action@v3
        with:
          username: ${{ env.OWNER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: KhiopsML/khiops-notebook
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            # Full version e.g. 10.3.2.0
            type=match,pattern=^\d+.\d+.\d+.\d+
            # Short version e.g. 10
            type=match,pattern=^(\d+).\d+.\d+.\d+,group=1
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run tests ‚úÖ
        run: python3 -m pytest tests

      - name: Build and push
        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule' || contains(github.ref, 'refs/tags')
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push - v11beta
        if: github.ref == 'refs/heads/11beta'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.SHA_TAG }}
            ${{ env.V11BETA_TAG }}
